config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  mount Knock::Engine => "/api"

  constraints CanAccessResque do
    mount Resque::Server, at: 'resque'
  end

  put '/settings', to: 'settings#update', as: 'settings'
  get '/settings', to: 'settings#edit', as: 'edit_settings'

  get '/comments_script', to: 'application#comments_script', as: 'comments_script'

  resources :apps, only: [:show, :index]

  root to: "artifacts#index"

  devise_for :users, ActiveAdmin::Devise.config.merge(:path => 'users',
    controllers: {
      passwords: 'users/passwords', registrations: 'users/registrations',
      sessions: 'users/sessions', omniauth_callbacks: 'users/auth_callbacks'
    }
  )

  devise_scope :user do
    post '/users/auth/', as: 'create_with_omniauth', controller: 'users/auth_callbacks', action: 'create_with_omniauth'
  end

  get 'my_artifacts', to: 'users#show', as: :my_artifacts

  resources :activities, only: [:index], as: 'activities'

  resources :artifacts
  get '/artifacts/:id/*filename', to: 'artifacts#download', as: :artifact_download, format: false

  post '/artifacts/:artifact_id/favorite/', to: 'favorites#create', as: :favorite_artifact, defaults: { format: :json }
  delete '/artifacts/:artifact_id/favorite/', to: 'favorites#destroy', as: :unfavorite_artifact, defaults: { format: :json }

  get '/hydrogen_drumkits', to: 'hydrogen_drumkits#index', as: 'hydrogen_drumkits', defaults: { format: :xml }

  get '/info/about', to: 'info#about', as: :info_about
  get '/info/contact', to: 'info#contact', as: :info_contact
  get '/info/survey', to: 'info#survey', as: :info_survey
  get '/analytics_optout', to: 'info#optout', as: :analytics_optout
  get '/terms_and_conditions', to: 'info#terms_and_conditions', as: :terms_and_conditions

  post '/locale/:locale', to: 'locales#set_locale', as: :set_locale

  # For licenses api
  resources :licenses, only: [:index], defaults: { format: :json }

  resources :searches, only: [], defaults: { format: :json } do
    collection do
      get :tags
      get '/apps', action: :software
      get :file_formats
    end
  end

  post '/notifications/:notification_type/dismiss', to: 'notifications#dismiss', defaults: { format: :json }

  ActiveAdmin.routes(self)
end

app/views/apps/_form.html.haml
= form_for @app do |f|
  - if @app.errors.any?
    #error_explanation
      %h2= "#{pluralize(@app.errors.count, "error")} prohibited this app from being saved:"
      %ul
        - @app.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :url
    = f.text_field :url
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/apps/edit.html.haml
%h1 Editing app

= render 'form'

= link_to 'Show', @app
\|
= link_to 'Back', apps_path

app/views/apps/index.html.haml
%h1 Listing apps

%table
  %thead
    %tr
      %th Name
      %th Url
      %th Description
      %th
      %th
      %th

  %tbody
    - @apps.each do |app|
      %tr
        %td= app.name
        %td= app.url
        %td= app.description
        %td= link_to 'Show', app
        %td= link_to 'Edit', edit_app_path(app)
        %td= link_to 'Destroy', app, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New App', new_app_path

app/views/apps/new.html.haml
%h1 New app

= render 'form'

= link_to 'Back', apps_path

app/views/apps/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @app.name
%p
  %b Url:
  = @app.url
%p
  %b Description:
  = @app.description

= link_to 'Edit', edit_app_path(@app)
\|
= link_to 'Back', apps_path